spring.application.name=project-api-gateway

server.port=8080

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8763/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Auth Service
spring.cloud.gateway.routes[0].id=AUTH-SERVICE
spring.cloud.gateway.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

# Application Service
spring.cloud.gateway.routes[1].id=APPLICATION-SERVICE
spring.cloud.gateway.routes[1].uri=lb://APPLICATION-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/applications/**
spring.cloud.gateway.routes[1].filters[0]=JwtAuthentication

# Certificate Service
spring.cloud.gateway.routes[2].id=CERTIFICATE-SERVICE
spring.cloud.gateway.routes[2].uri=lb://CERTIFICATE-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/certificates/**
spring.cloud.gateway.routes[2].filters[0]=JwtAuthentication

# Verification Service
spring.cloud.gateway.routes[3].id=VERIFICATION-SERVICE
spring.cloud.gateway.routes[3].uri=lb://VERIFICATION-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/verify/**

# JWT Secret
jwt.secret=VGhpcy1pcy1hLXN1ZmZpY2llbnQtc2VjcmV0LWtleS0yMDI2